server:
  port: 8081

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
    content-type: text/html
    mode: LEGACYHTML5