server.port: ${random.int[10000,19999]}
spring.application.name: admin-client
logging.level.root: info
management.endpoints.web.exposure.include: "*"


spring.boot.admin.client:
    url: http://localhost:10001
    instance:
      metadata:
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}