server.port: 9090
spring.application.name: validator
logging.level.root: INFO


management.endpoints.web.exposure.include: "*"
spring.mvc.throw-exception-if-no-handler-found: true
#spring:
#  resources:
#    add-mappings: false