#server.port: ${random.int[10000,19999]}
spring.application.name: spring-greeting
logging.level.root: debug


#management.endpoints.web.exposure.include: "*"


spring.boot.admin.client.url: http://localhost:10001
server:
  port: 8081
